sudo: required
services:
  - docker

before_install:
  - docker build -t ecastroaleman/react-test -f ./client/Dockerfile.dev ./client
 

script:
  - docker run ecastroaleman/react-test npm test -- --coverage


after_success:
  - docker build -t ecastroaleman/multi-client ./client
  - docker build -t ecastroaleman/multi-nginx ./nginx
  - docker build -t ecastroaleman/multi-server ./server
  - docker build -t ecastroaleman/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push ecastroaleman/multi-client
  - docker push ecastroaleman/multi-nginx
  - docker push ecastroaleman/multi-server
  - docker push ecastroaleman/multi-worker
